image: rust:1.26

stages:
  - build

# Avoid rebuilding deps if we don't need to
cache:
  paths:
  - ~/.cargo/
  - target/

build:
  stage: build
  script:
  - cargo build --release
  - strip target/release/mc-wrap
  artifacts:
    paths:
    - target/release/mc-wrap
